---
driver_config:
  require_chef_omnibus: true

platforms:
  - name: vagrant-ubuntu-13.04
    driver_plugin: vagrant
    driver_config:
      box: opscode-ubuntu-13.04
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-13.04_chef-provisionerless.box

suites:
- name: host
  run_list: ['minitest-handler', 'clone-me_test::default']
  attributes: {}
