---
driver_config:
  require_chef_omnibus: true

platforms:
  - name: vagrant-ubuntu-12.04
    driver_plugin: vagrant
    driver_config:
      box: opscode-ubuntu-12.04
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box

suites:
- name: host
  run_list: ['minitest-handler', 'clone-me_test::default']
  attributes: {}
